spring:
  data:
    mongodb:
      uri: mongodb://agencia_viajes:password@localhost:28017/agencia_viajes?authSource=admin
  application:
    name: basic-service-mongodb
server:
  port: ${SERVER_PORT:8082}
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
