spring:
  data:
    mongodb:
      host: localhost
      port: 27017
  application:
    name: hotel_service
server:
  port: ${SERVER_PORT:8082}
eureka:
  client:
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
